// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGY-CYuAIMpUPFolBo-jRs-OB6M9jXkQg',
    appId: '1:204582928566:web:da5f28d38a128a00436617',
    messagingSenderId: '204582928566',
    projectId: 'astrolex-app',
    authDomain: 'astrolex-app.firebaseapp.com',
    storageBucket: 'astrolex-app.appspot.com',
    measurementId: 'G-HF8JCFYEXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbpYeV_LMwTVWHtEtSyi99Sj49r_UxgE',
    appId: '1:204582928566:android:90eefe5963f15e94436617',
    messagingSenderId: '204582928566',
    projectId: 'astrolex-app',
    storageBucket: 'astrolex-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi2nTWtvXrl0A3c0mlV3P4pQb8Mm4s3-8',
    appId: '1:204582928566:ios:b6ef51df8a0acaa7436617',
    messagingSenderId: '204582928566',
    projectId: 'astrolex-app',
    storageBucket: 'astrolex-app.appspot.com',
    iosBundleId: 'com.cotr.astrolex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi2nTWtvXrl0A3c0mlV3P4pQb8Mm4s3-8',
    appId: '1:204582928566:ios:11d998ca3ebaf6cf436617',
    messagingSenderId: '204582928566',
    projectId: 'astrolex-app',
    storageBucket: 'astrolex-app.appspot.com',
    iosBundleId: 'com.cotr.astrolex.RunnerTests',
  );
}
